services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means

    Owp\OwpCore\:
        resource: '../../*'
        exclude: '../{DependencyInjection,Entity,Migrations,Tests,Resources,OwpCoreBundle.php}'

    Owp\OwpCore\EventListener\:
        resource: '../../EventListener'
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Owp\OwpCore\Twig\:
        resource: '../../Twig'
        tags: ['twig.runtime']

    Owp\OwpCore\Command\:
        resource: '../../Command'
        tags: ['console.command']

    admin.link:
        class: Owp\OwpCore\Admin\LinkAdmin
        arguments: [~, Owp\OwpCore\Entity\Link, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: referentiel, label: "Liens utiles" }

    admin.menu:
        class: Owp\OwpCore\Admin\MenuAdmin
        arguments: [~, Owp\OwpCore\Entity\Menu, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: referentiel, label: "Items du menu" }

    admin.user:
        class: Owp\OwpCore\Admin\UserAdmin
        arguments: [~, Owp\OwpCore\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "Utilisateurs" }

    sonata.block.admin_stat:
        class: Owp\OwpCore\Block\AdminStatBlock
        arguments:
            - '@twig'
            - '@templating'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: sonata.block }

    sonata.block.link:
        class: Owp\OwpCore\Block\LinkBlock
        arguments:
            - '@twig'
            - '@templating'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: sonata.block }

    sonata.block.menu:
        class: Owp\OwpCore\Block\MenuBlock
        arguments:
            - '@twig'
            - '@templating'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: sonata.block }
